version: "3.9"

services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: src/docker/Dockerfile.api
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app/src
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: src/docker/Dockerfile.worker
    working_dir: /app
    environment:
      PYTHONPATH: /app/src
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    depends_on:
      - redis

  generator:
    build:
      context: .
      dockerfile: src/docker/Dockerfile.generator
    working_dir: /app
    environment:
      PYTHONPATH: /app/src
      API_URL: ${API_URL}
    depends_on:
      - api