FROM python:3.10-slim

WORKDIR /app

# copy requirements FIRST (important for caching)
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# copy full project
COPY . .

ENV PYTHONPATH=/app

CMD ["uvicorn", "src.services.api.main:app", "--host", "0.0.0.0", "--port", "8000"]